site_name: DigiLut Challenge
site_description: Official documentation of digilut

# Repository
repo_name: Github
repo_url: https://github.com/LouisStefanuto/digilut

theme:
  name: material
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: indigo
  features:
      - navigation.tabs
      - navigation.tabs.sticky

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LouisStefanuto/digilut

markdown_extensions:
  # nested boxes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # colored boxes to highlight key points
  - admonition
  # make colored boxes collapsible
  - pymdownx.details
  # for menu fancy grid-organized boxes
  - attr_list
  - md_in_html
  # emojis from Material
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji # to add emojis
      emoji_generator: !!python/name:material.extensions.emoji.to_svg # to add LateX
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  # to add LateX
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Home: index.md
  - Install:
    - Local install: install.md
    - Install on the Trustii platform: trustii.md
  - Challenge: challenge.md
  - Training: approach.md
  - Results: results.md
  - Post Processing: postprocessing.md
  - CLI:
    - Menu CLI: cli/index.md
    - New to Typer?: cli/new_to_typer.md
    - Commands: cli/commands.md
  - Run: run.md
  - References: references.md
  - About: about.md
